vich_uploader:
    db_driver: orm
    mappings:
        ingredients_images:
            uri_prefix: '/ingredients/images'
            upload_destination: '%kernel.project_dir%/public/ingredients/images'
        recipe_images:
                uri_prefix: '/recipe/images'
                upload_destination: '%kernel.project_dir%/public/recipe/images'
        blog_images:
                uri_prefix: '/blog/images'
                upload_destination: '%kernel.project_dir%/public/blog/images'
        learn_images:
                uri_prefix: '/learn/images'
                upload_destination: '%kernel.project_dir%/public/learn/images'        

