vich_uploader:
    db_driver: orm

    mappings:
        recipes:
            uri_prefix: /images/recipes
            upload_destination: '%kernel.project_dir%/public/images/recipes'
        category:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'
