vich_uploader:
    db_driver: orm
    mappings:
        ingredients_images:
            uri_prefix: '/ingredients/images'
            upload_destination: '%kernel.project_dir%/public/ingredients/images'

